[window]

opacity = 0.9

padding.x = 1
padding.y = 1

decorations = "Full"
decorations_theme_variant = "Dark"

[font]

normal.family = "3270 Nerd Font"
bold.family = "3270 Nerd Font"
italic.family = "3270 Nerd Font"
bold_italic.family = "3270 Nerd Font"

size = 16
